---
title: "Natural selection"
output: html_document
date: "2024-09-19"
---

```{r natural selection, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Natural selection

## Backgrounds

The living world is rich with diversity. This diversity is often examined at the level of species, with over 1.5 million species described and estimates of the total number of species on Earth ranging from 5 to 100 million (estimates vary greatly; see figure below). Yet diversity also exists within species, populations, social units, and family lineages. Variability in the features of organisms that we see today is put into even greater perspective when one considers the vast amount of diversity that occurred in previous generations. Only a fraction of this remains recorded in the fossil record. 

Fossils suggest that the number of species has increased over time, although some relatively brief periods of decrease are also recorded. Records also suggest that characteristics have become more complex over time. There are numerous hypotheses that could explain the origin and diversification of species. Some attribute it to divine intervention, some to extraterrestrial influence, and still others to simple physical and chemical processes that occurred in our primordial backyards. 

Regardless of what caused the origin and initial diversification of life, ecologists are generally curious about the sources of diversity within modern populations, and knowing what causes this diversity to be maintained, increased, or eliminated from populations. Indeed, the entire field of conservation biology is devoted to understanding and preserving natural variation within and among groups of organisms.

**Key Terms**: (you’ll want to be sure to use these in your lab report!)

*Natural selection*: the process by which organisms better adapted to their environment are able to survive for longer and produce more offspring.

*Fitness*: an organism’s relative likelihood of surviving long enough to pass on its genes. In other words, those who contribute most to the next generation exhibit the highest fitness.

*Selective environment*: an organism’s environment plays a role in selecting favorable traits, and traits that get selected for may be different depending on the nature of each environment.

*Selective agent*: a biological or physical agent that imposes selection, and thereby determines which individuals pass on genes and which do not.

## Objectives

To understand how natural selection operates and characteristics within and among populations change over time, and to answer the following research question (especially in your lab report):

## Research question: 
Does the selective environment affect the composition of future generations? 

## Methods

*Materials*

Each group of three should have: 
1 piece of patterned fabric
7 different colors of dots (approximately 80 of each color, kept in separate piles)
Green bowl (for discarding dots)
Note-taking materials

*Procedure*

1.	With your group members, read through the entire procedure. Based on what you now know about the experiment, formulate a hypothesis. Write it down for inclusion in your lab report. 

2.	Each group of three to four should select a fabric pattern of its choice (it’s OK if two or more groups use the same pattern) and get *seven* piles of differently colored paper dots (keep colors separate; colors include black, hot pink, green, pink/peach, dark yellow, white, blue). 

3.	Count out 12 dots of each color, and mix them in a single dish.

4.	Spread the fabric flat on a table and randomly sprinkle the 84 dots onto the fabric. Be sure to disperse the dots all over the fabric, not just in a small group on one part of the fabric. 

5. On the spreadsheet provided here, record the frequency of each type of colored dot. [Download the CSV file](downloads/naturalselectiondatasheet.csv)

6.	Imagine each group member is a red-tailed hawk, and that each colored dot is a mouse with a particular fur color. Each mouse runs free in its respective environment, while each hawk preys on the mice. Hawks can only prey on one mouse at a time. A hawk must “fly” the mouse back to its nest (another culture dish) each time it captures one. The hawks must hunt quickly – you will only have 45 seconds to remove 56 mice!

7.	In the first year of predation, the hawks remove 56 mice from the population (thus, 28 mice remain in the population).  Group members will remove the first 56 dots they see  in 45 seconds. If you need more than 45 seconds, keep going until you remove 56, just try to go as quick as you can while following the instructions!

8.	Remove the 28 survivors from the fabric as well. Each of the survivors “overwinters” and has two offspring of the same color. Count out these new mice and incorporate them into the population. [If this requires hole-punching more of a particular color, feel free to do so.] After they’ve been incorporated, record the frequency in Table 1 of each fur color in the population (note: the population size after the new mice are incorporated should again be 84, but the frequencies of the fur colors might be different than those recorded in Step 4 of this investigation). Again, randomly sprinkle the 84 dots onto the fabric.

9.	Repeat Steps 6 -8 three times, recording the frequency of fur colors for each generation. After the third iteration of hawks preying on the population, count the remaining mice (those that would make up the fourth generation) and record in Table 1. Next to your first graph, make a bar graph showing the frequency of each type of colored dot in the final generation. Copy the two graphs into your lab report. 

10.	Compare the frequencies of fur colors (dot colors) in the first generation to those in the fourth generation. 

11.	If the frequencies of fur color changed in the population over time, then within your group and with everyday language describe the phenomenon that was responsible for the change. 

12. Graph your results [Download the R file](downloads/NaturalSelection.R)

## What to turn in

*Lab Report Due in 1 week on Canvas*

Your final product will be a lab report containing only research question, hypothesis, methods, and results (Format 1) as described in the “Written Lab Report Guidelines” on Canvas. 

Only use the data from your group of hawks and habitat. Compare the distribution of mice fur colors between the first, second, third and fourth generation to answer the research question and address how your results aligned with your hypothesis. Describe your data collection methods (outlined above) and your results. **You must include one table and one set of figures based on today’s results.**

Next week, you will turn in a completed lab report to your instructor through Canvas in which you have made your best effort to write up those components of a lab report. Then, your instructor will provide you with feedback by the following week’s class. 

